"""Add therapist_category to User

Revision ID: 393c26d76d36
Revises: c896b9ac960e
Create Date: 2026-03-27 19:17:06.912491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '393c26d76d36'
down_revision: Union[str, None] = 'c896b9ac960e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('therapist_category', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'therapist_category')
    # ### end Alembic commands ###
