"""Add participant gender

Revision ID: 3e81293afc3c
Revises: c69a3be4a923
Create Date: 2026-04-07 21:21:49.748195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e81293afc3c'
down_revision: Union[str, None] = 'c69a3be4a923'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('gender', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'gender')
    # ### end Alembic commands ###
