"""Add session status

Revision ID: c69a3be4a923
Revises: bfde96ea7644
Create Date: 2026-04-07 19:38:43.177708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69a3be4a923'
down_revision: Union[str, None] = 'bfde96ea7644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('status', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'status')
    # ### end Alembic commands ###
